// Generated by CoffeeScript 1.10.0
(function() {
  var addNewItem, butAdd, name, output;

  name = "Elvine";

  output = document.getElementById("coffeeOutput");

  output.innerHTML = "Hello " + name;

  butAdd = document.getElementById("addItem");

  butAdd.innerHTML = "Add Item";

  addNewItem = function(list, itemText) {
    var checkbox, listItem;
    listItem = document.createElement("li");
    checkbox = document.createElement("input");
    checkbox.type = "checkbox";
    listItem.appendChild(checkbox);
    listItem.innerHTML = listItem.innerHTML + itemText;
    list.appendChild(listItem);
    return listItem;
  };

  butAdd = document.getElementById("addItem");

  butAdd.onclick = function() {
    var itemText;
    itemText = prompt("Add new item ");
    return addNewItem(document.getElementById("todoList"), itemText);
  };

}).call(this);
